export default [{
  "key": 1,
  "label": "首页",
  "value": false
}, {
  "key": 2,
  "label": "系统管理",
  "value": false,
  "children": [{
    "key": 6,
    "label": "职位管理",
    "value": false,
    "children": [{
      "key": 33,
      "label": "新增",
      "value": true
    }, {
      "key": 34,
      "label": "查看",
      "value": false
    }, {
      "key": 35,
      "label": "编辑",
      "value": false
    }, {
      "key": 36,
      "label": "授权",
      "value": false
    }, {
      "key": 37,
      "label": "启用/停用",
      "value": false
    }, {
      "key": 38,
      "label": "删除",
      "value": false
    }]
  }, {
    "key": 9,
    "label": "员工管理",
    "value": false,
    "children": [{
      "key": 39,
      "label": "新增",
      "value": false
    }, {
      "key": 40,
      "label": "查看",
      "value": false
    }, {
      "key": 41,
      "label": "密码重置",
      "value": false
    }, {
      "key": 42,
      "label": "启用/停用",
      "value": false
    }, {
      "key": 43,
      "label": "删除",
      "value": false
    }, {
      "key": 94,
      "label": "编辑",
      "value": false
    }]
  }]
}, {
  "key": 10,
  "label": "基础资料",
  "value": false,
  "children": [{
    "key": 11,
    "label": "客商管理",
    "value": false,
    "children": [{
      "key": 70,
      "label": "新增",
      "value": false
    }, {
      "key": 71,
      "label": "查看",
      "value": false
    }, {
      "key": 72,
      "label": "编辑",
      "value": false
    }, {
      "key": 73,
      "label": "密码重置",
      "value": false
    }, {
      "key": 74,
      "label": "启用/停用",
      "value": false
    }, {
      "key": 75,
      "label": "删除",
      "value": false
    }]
  }, {
    "key": 13,
    "label": "货物管理",
    "value": false,
    "children": [{
      "key": 66,
      "label": "新增",
      "value": false
    }, {
      "key": 67,
      "label": "查看",
      "value": false
    }, {
      "key": 68,
      "label": "编辑",
      "value": false
    }, {
      "key": 69,
      "label": "删除",
      "value": false
    }]
  }, {
    "key": 14,
    "label": "类别管理",
    "value": false,
    "children": [{
      "key": 56,
      "label": "新增",
      "value": false
    }, {
      "key": 57,
      "label": "编辑",
      "value": false
    }, {
      "key": 58,
      "label": "删除",
      "value": false
    }]
  }, {
    "key": 15,
    "label": "规格管理",
    "value": false,
    "children": [{
      "key": 63,
      "label": "新增",
      "value": false
    }, {
      "key": 64,
      "label": "编辑",
      "value": false
    }, {
      "key": 65,
      "label": "删除",
      "value": false
    }]
  }, {
    "key": 16,
    "label": "材质管理",
    "value": false,
    "children": [{
      "key": 60,
      "label": "新增",
      "value": false
    }, {
      "key": 61,
      "label": "编辑",
      "value": false
    }, {
      "key": 62,
      "label": "删除",
      "value": false
    }]
  }, {
    "key": 18,
    "label": "仓库管理",
    "value": false,
    "children": [{
      "key": 44,
      "label": "新增",
      "value": false
    }, {
      "key": 45,
      "label": "查看",
      "value": false
    }, {
      "key": 46,
      "label": "删除",
      "value": false
    }, {
      "key": 47,
      "label": "编辑",
      "value": false
    }]
  }, {
    "key": 19,
    "label": "仓区设置",
    "value": false,
    "children": [{
      "key": 48,
      "label": "新增",
      "value": false
    }, {
      "key": 49,
      "label": "查看",
      "value": false
    }, {
      "key": 50,
      "label": "编辑",
      "value": false
    }, {
      "key": 51,
      "label": "删除",
      "value": false
    }]
  }, {
    "key": 20,
    "label": "仓位设置",
    "value": false,
    "children": [{
      "key": 52,
      "label": "新增",
      "value": false
    }, {
      "key": 53,
      "label": "查看",
      "value": false
    }, {
      "key": 54,
      "label": "编辑",
      "value": false
    }, {
      "key": 55,
      "label": "删除",
      "value": false
    }]
  }, {
    "key": 95,
    "label": "费用项管理",
    "value": false
  }]
}, {
  "key": 21,
  "label": "出入库管理",
  "value": false,
  "children": [{
    "key": 22,
    "label": "入库申请",
    "value": false,
    "children": [{
      "key": 76,
      "label": "查看",
      "value": false
    }, {
      "key": 77,
      "label": "查看单据明细",
      "value": false
    }, {
      "key": 78,
      "label": "审核",
      "value": false
    }, {
      "key": 79,
      "label": "生成明细",
      "value": false
    }]
  }, {
    "key": 23,
    "label": "出库申请",
    "value": false,
    "children": [{
      "key": 80,
      "label": "查看",
      "value": false
    }, {
      "key": 81,
      "label": "查看单据明细",
      "value": false
    }, {
      "key": 82,
      "label": "审核",
      "value": false
    }, {
      "key": 83,
      "label": "生成明细",
      "value": false
    }]
  }, {
    "key": 24,
    "label": "入库管理",
    "value": false,
    "children": [{
      "key": 30,
      "label": "新增",
      "value": false
    }, {
      "key": 31,
      "label": "查看",
      "value": false
    }]
  }, {
    "key": 25,
    "label": "出库管理",
    "value": false,
    "children": [{
      "key": 84,
      "label": "新增",
      "value": false
    }, {
      "key": 85,
      "label": "查看",
      "value": false
    }]
  }]
}, {
  "key": 26,
  "label": "库存管理",
  "value": false,
  "children": [{
    "key": 27,
    "label": "库存盘点",
    "value": false,
    "children": [{
      "key": 86,
      "label": "新增",
      "value": false
    }, {
      "key": 87,
      "label": "删除",
      "value": false
    }, {
      "key": 88,
      "label": "录入",
      "value": false
    }, {
      "key": 89,
      "label": "查看",
      "value": false
    }]
  }, {
    "key": 28,
    "label": "移库管理",
    "value": false,
    "children": [{
      "key": 90,
      "label": "新增",
      "value": false
    }, {
      "key": 91,
      "label": "删除",
      "value": false
    }, {
      "key": 92,
      "label": "审核",
      "value": false
    }, {
      "key": 93,
      "label": "查看",
      "value": false
    }]
  }, {
    "key": 29,
    "label": "库存列表",
    "value": false
  }]
}]